
application: nerva2py   # change the field to the project name or app id!
version: 1
api_version: 1
runtime: python27

threadsafe: true
default_expiration: "24h"   # for static files

handlers:

- url: /favicon.ico
  static_files: applications/nerva2py/static/favicon.ico
  upload: applications/nerva2py/static/favicon.ico

- url: /robots.txt
  static_files: applications/nerva2py/static/robots.txt
  upload: applications/nerva2py/static/robots.txt

- url: .*
  script: gaehandler.wsgiapp
  secure: optional

admin_console:
  pages:
  - name: Appstats
    url: /_ah/stats

builtins:
- remote_api: on
- appstats: on
- admin_redirect: on
- deferred: on



